# Generated by Django 2.2 on 2020-01-24 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20, unique=True)),
                ('verify', models.BooleanField(default=False)),
                ('email', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_name', models.CharField(max_length=50)),
                ('item_quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('product_description', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='farmers')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporate.ContactModel')),
            ],
        ),
        migrations.CreateModel(
            name='Corporate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=30)),
                ('access_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporate.ContactModel')),
            ],
        ),
        migrations.CreateModel(
            name='CorperateGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='download.jpg', upload_to='groups')),
                ('price', models.FloatField(blank=True, default=0)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporate.ContactModel')),
                ('user', models.ManyToManyField(blank=True, null=True, to='corporate.Items')),
            ],
        ),
    ]
